#!/bin/sh

LIBDIR='/usr/lib/lime-tools'
DATADIR='/usr/share/lime-tools'
SYSCONFDIR='/etc/lime-tools'

export LC_MESSAGES=C
export LANG=C

livetimer=$(date +%s%3N)

[[ -r ${LIBDIR}/util-live.sh ]] && source ${LIBDIR}/util-live.sh

livetimer=$(get_timer_ms)
CONSOLEFONT="$(kernel_cmdline vconsole.font)"
CONSOLEMAP="$(kernel_cmdline vconsole.font.map)"
arch=$(uname -m)
echo "Got consolefont and arch $arch: $(elapsed_time_ms ${livetimer})ms" >> /var/log/lime-live.log

# Activate swap
livetimer=$(get_timer_ms)
configure_swap
echo "Activated swap and added to fstab: $(elapsed_time_ms ${livetimer})ms" >> /var/log/lime-live.log

livetimer=$(get_timer_ms)
configure_language
echo "Languaged configured: $(elapsed_time_ms ${livetimer})ms" >> /var/log/lime-live.log

livetimer=$(get_timer_ms)
configure_clock
echo "Configured clock: $(elapsed_time_ms ${livetimer})ms" >> /var/log/lime-live.log

livetimer=$(get_timer_ms)
configure_user_root /
echo "Configured root user: $(elapsed_time_ms ${livetimer})ms" >> /var/log/lime-live.log

livetimer=$(get_timer_ms)
# load dm-mod
modprobe dm-mod
echo "Load dm-mod: $(elapsed_time_ms ${livetimer})ms" >> /var/log/lime-live.log

